name: "DarkLog"
author: "devsimsek"
version: "v1.0"

snippets:
  home_post: '<article>
    <section class="post-info">
        <h3 id="post-title" class="post-heading"><a href="/post/[[file]].html">[[title]]</a></h3>
        <div class="flex-inline">
            <span class="date"><i class="bi bi-calendar-date"></i> [[date]]</span>
        </div>
    </section>
    <section class="post">
        [[body]]
    </section>
    </article>'